# Generated by Django 2.2.5 on 2020-02-08 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfUsuario_rol',
            fields=[
                ('id_usuario_rol', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': ('Rol de usuario',),
                'verbose_name_plural': ('Roles de usuarios',),
                'db_table': 'usuario_rol',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('id_padre', models.IntegerField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name': ('Menu',),
                'verbose_name_plural': ('Menus',),
                'db_table': 'conf_menu',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id_modulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': ('Modulos',),
                'verbose_name_plural': ('Modulos',),
                'db_table': 'conf_modulo',
            },
        ),
        migrations.CreateModel(
            name='modulo_menu',
            fields=[
                ('id_modulo_menu', models.AutoField(primary_key=True, serialize=False)),
                ('id_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fkMenuModulo', to='configuraciones.Menu')),
                ('id_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fkRolMenu', to='configuraciones.Modulo')),
            ],
            options={
                'verbose_name': ('Menu',),
                'verbose_name_plural': ('Menus',),
                'db_table': 'conf_modulo_menu',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': ('Persona',),
                'verbose_name_plural': ('Personas',),
                'db_table': 'mant_persona',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': ('Rol',),
                'verbose_name_plural': ('Roles',),
                'db_table': 'conf_rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=50)),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_persona', to='configuraciones.Persona')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.Rol')),
            ],
            options={
                'verbose_name': ('Usuario',),
                'verbose_name_plural': ('Usuarios',),
                'db_table': 'conf_usuario',
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('moduloMenu', models.ForeignKey(db_column='id_modulo_menu', on_delete=django.db.models.deletion.CASCADE, related_name='fk_mod_menu', to='configuraciones.modulo_menu')),
                ('usuario_rol', models.ForeignKey(db_column='id_usuario_rol', on_delete=django.db.models.deletion.CASCADE, related_name='fk_usurol', to='configuraciones.ConfUsuario_rol')),
            ],
            options={
                'verbose_name': ('Permiso',),
                'verbose_name_plural': ('Permisos',),
                'db_table': 'permisos',
            },
        ),
        migrations.AddField(
            model_name='confusuario_rol',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, related_name='fkrol_usuario', to='configuraciones.Rol'),
        ),
        migrations.AddField(
            model_name='confusuario_rol',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='fkusuario_rol', to='configuraciones.Usuario'),
        ),
    ]
