# Generated by Django 2.2.5 on 2020-02-08 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0002_remove_usuario_id_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo_menu',
            name='id_menu',
        ),
        migrations.RemoveField(
            model_name='modulo_menu',
            name='id_modulo',
        ),
        migrations.RemoveField(
            model_name='permisos',
            name='moduloMenu',
        ),
        migrations.AddField(
            model_name='permisos',
            name='menu',
            field=models.ForeignKey(db_column='id_menu', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fk_mod_menu', to='configuraciones.Menu'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Modulo',
        ),
        migrations.DeleteModel(
            name='modulo_menu',
        ),
    ]
