# Generated by Django 2.2.5 on 2020-02-08 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id_rol',
        ),
    ]
